version: '2'
services:
  
  api:
    image: strapi/strapi
    volumes:
      - .:/srv/app
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: toor
    ports:
      - 1337:1337
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_ROOT_PASSWORD: toor

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
    ports:
      - 8080:80
    depends_on:
      - mariadb